### ISSUE TITLE
A Reflected XSS vulnerability in unaired.php

### ISSUE THREAD

**Issue by jgj212** [TheFirstQuestion/HelpMeWatchWho#1]
Hello:
I have find a Reflected XSS vulnerability.

The vulnerability exists due to insufficient filtration of user-supplied data in "episodeID" HTTP parameter that will be passed to "HelpMeWatchWho-master/unaired.php". The infected source code is line 4, there is no protection on $_GET['episodeID'], if it contains evil js code, line 42 will trigger untrusted code to be executed on the browser side.
 ![1](https://cloud.githubusercontent.com/assets/1484292/24281145/3efa8d4a-1091-11e7-8c80-45d3ee9103a8.png)

So if a attacker construct a special url as follow and send it to a victim, when the victim click the url, the code which is contained in the url will be executed on the victim's browser side to do some evil.
http://your-web-root/HelpMeWatchWho-master/unaired.php?episodeID='/><script>alert(1);</script><"

The follow scrrenshot is the result to click the upper url ( win7 sp1 x64 + firefox 51.0.1 32bit ):
![2](https://cloud.githubusercontent.com/assets/1484292/24281152/503fcc14-1091-11e7-96c1-2db57d57872e.png)
 
Discoverer: ADLab of Venustech

**Comment by TheFirstQuestion** [comment]
Thank you for pointing this out! This issue was resolved in the most recent commit (e23a510).
